export const ADD_STORE = 'ADD_STORE';
export const ADD_STORE_SUCCESS = 'ADD_STORE_SUCCESS';
export const ADD_STORE_FAILURE = 'ADD_STORE_FAILURE';



export const START_DOWNLOAD_STORES = 'START_DOWNLOAD_STORES';
export const DOWNLOAD_STORES_SUCCESS = 'DOWNLOAD_STORES_SUCCESS';
export const DOWNLOAD_STORES_FAILURE = 'DOWNLOAD_STORES_FAILURE';